In [1]:
# Import libraries
import numpy as np

# Define constants
pi = np.pi

In [2]:
# Part a. Interior points

E = 210
v = 0.3

c11 = E*(1-v)/((1+v)*(1-2*v))
c12 = E*v/((1+v)*(1-2*v))
c44 = E/(2*(1+v))

#c11 = 45
#c12 = 11
#c44 = 17

mu = c44
nu = c12/(2*(c44+c12))
lambda_ = 2*mu*nu/(1-2*nu)

eps11 = 0.001
eps22 = 0.001
eps33 = 0.001
eps12 = 0.0
eps13 = 0.0
eps23 = 0.0

eps21 = eps12
eps32 = eps23
eps31 = eps13

a1 = 24
a2 = a1
a3 = 0.5*a1

I1 = ((2*pi*(a1**2)*a3)/(a1**2 - a3**2)**1.5)*(np.arccos(a3/a1) - (a3/a1)*np.sqrt(1 - (a3/a1)**2))
I2 = I1
I3 = 4*pi - 2*I1

I12 = pi/a1**2 - (I1-I3)/(4*(a3**2 - a1**2))
I11 = I12
I22 = I11
I13 = (I1-I3)/(a3**2 - a1**2)
I23 = I13
I33 = (4*pi/a3**2 - 2*I13)/3
I21 = I12
I31 = I13
I32 = I23

#Calculate sigma11
t11 = (a1**2)*(3*I11 - 3*nu*I11 + nu*I21 + nu*I31)/(8*pi*(1-nu)*(1-2*nu))
t12 = (1-2*nu)*(I1-nu*(I1+I2+I3))/(8*pi*(1-nu)*(1-2*nu))
t13 = (1-nu)/(1-2*nu)
t1 = (t11 + t12 - t13)*eps11

t21 = (a2**2)*(I12 - nu*I12 + 3*nu*I22 + nu*I32)/(8*pi*(1-nu)*(1-2*nu))
t22 = (1-2*nu)*(I1-nu*(I1+I2-I3))/(8*pi*(1-nu)*(1-2*nu))
t23 = (nu)/(1-2*nu)
t2 = (t21 - t22 - t23)*eps22

t31 = (a3**2)*(I13 - nu*I13 + nu*I23 + 3*nu*I33)/(8*pi*(1-nu)*(1-2*nu))
t32 = (1-2*nu)*(I1-nu*(I1-I2+I3))/(8*pi*(1-nu)*(1-2*nu))
t33 = (nu)/(1-2*nu)
t3 = (t31 - t32 - t33)*eps33

sig11 = (t1 + t2 + t3)*2*mu

#calculate sigma22 using cyclic permutation of 1,2,3
t22 = (a2**2)*(3*I22 - 3*nu*I22 + nu*I32 + nu*I12)/(8*pi*(1-nu)*(1-2*nu))
t23 = (1-2*nu)*(I2-nu*(I2+I3+I1))/(8*pi*(1-nu)*(1-2*nu))
t21 = (1-nu)/(1-2*nu)
t2 = (t22 + t23 - t21)*eps22

t32 = (a3**2)*(I23 - nu*I23 + 3*nu*I33 + nu*I13)/(8*pi*(1-nu)*(1-2*nu))
t33 = (1-2*nu)*(I2-nu*(I2+I3-I1))/(8*pi*(1-nu)*(1-2*nu))
t31 = (nu)/(1-2*nu)
t3 = (t32 - t33 - t31)*eps33

t12 = (a1**2)*(I21 - nu*I21 + nu*I31 + 3*nu*I11)/(8*pi*(1-nu)*(1-2*nu))
t13 = (1-2*nu)*(I2-nu*(I2-I3+I1))/(8*pi*(1-nu)*(1-2*nu))
t11 = (nu)/(1-2*nu)
t1 = (t12 - t13 - t11)*eps11

sig22 = (t2 + t3 + t1)*2*mu

#calculate sigma33 using cyclic permutation of 1,2,3
t33 = (a3**2)*(3*I33 - 3*nu*I33 + nu*I13 + nu*I23)/(8*pi*(1-nu)*(1-2*nu))
t31 = (1-2*nu)*(I3-nu*(I3+I1+I2))/(8*pi*(1-nu)*(1-2*nu))
t32 = (1-nu)/(1-2*nu)
t3 = (t33 + t31 - t32)*eps33

t13 = (a1**2)*(I31 - nu*I31 + 3*nu*I11 + nu*I21)/(8*pi*(1-nu)*(1-2*nu))
t11 = (1-2*nu)*(I3-nu*(I3+I1-I2))/(8*pi*(1-nu)*(1-2*nu))
t12 = (nu)/(1-2*nu)
t1 = (t13 - t11 - t12)*eps11

t23 = (a2**2)*(I32 - nu*I32 + nu*I12 + 3*nu*I22)/(8*pi*(1-nu)*(1-2*nu))
t21 = (1-2*nu)*(I3-nu*(I3-I1+I2))/(8*pi*(1-nu)*(1-2*nu))
t22 = (nu)/(1-2*nu)
t2 = (t23 - t21 - t22)*eps22

sig33 = (t3 + t1 + t2)*2*mu

print(sig11,sig22,sig33)

#calculate sigma12 using cyclic permutation of 1,2,3
t11 = (a1**2 + a2**2)*I12/(8*pi*(1-nu))
t12 = (1-2*nu)*(I1+I2)/(8*pi*(1-nu))
t13 = 1
sig12 = (t11 + t12 - t13)*eps12*2*mu

#calculate sigma23 using cyclic permutation of 1,2,3
t22 = (a2**2 + a3**2)*I23/(8*pi*(1-nu))
t23 = (1-2*nu)*(I2+I3)/(8*pi*(1-nu))
t21 = 1
sig23 = (t22 + t23 - t21)*eps23*2*mu

#calculate sigma31 using cyclic permutation of 1,2,3
t33 = (a3**2 + a1**2)*I31/(8*pi*(1-nu))
t31 = (1-2*nu)*(I3+I1)/(8*pi*(1-nu))
t32 = 1
sig31 = (t33 + t31 - t32)*eps31*2*mu

print(sig12,sig23,sig31)

#print(sig12,sig23,sig31)
sig21 = sig12
sig32 = sig23
sig13 = sig31

sig_in = np.array([[sig11,sig12,sig13],[sig21,sig22,sig23],[sig31,sig32,sig33]])
sigma = np.zeros((3,3))
delta = np.zeros((3,3))
for i in range(3):
    delta[i,i] = 1

-0.2290800423843854 -0.2290800423843854 -0.14183991523122905
-0.0 -0.0 -0.0


In [3]:
# Jump Conditions

#NN is directions of normal vectors
nn = np.zeros((3,1))
nn[0] = 1
nn[1] = 0
nn[2] = 0

nk = np.sqrt(nn[0]**2 + nn[1]**2 + nn[2]**2)

epss = np.array([[eps11,eps12,eps13],[eps21,eps22,eps23],[eps31,eps32,eps33]])

C = np.zeros((3,3,3,3))
C[0,0,0,0] = c11
C[0,0,1,1] = c12
C[0,1,0,1] = c44

C[1,1,1,1] = c11
C[2,2,2,2] = c11

C[1,1,0,0] = c12
C[2,2,0,0] = c12
C[0,0,2,2] = c12
C[1,1,2,2] = c12
C[2,2,1,1] = c12

C[0,1,1,0] = c44
C[1,0,0,1] = c44
C[1,0,1,0] = c44
C[0,2,0,2] = c44
C[2,0,2,0] = c44
C[2,0,0,2] = c44
C[0,2,2,0] = c44
C[1,2,1,2] = c44
C[2,1,2,1] = c44
C[2,1,1,2] = c44
C[1,2,2,1] = c44

In [4]:
# K_cof

K_cof = np.zeros((3,3))

for i in range(3):
    for j in range(3):
        for k in range(3):
            for l in range(3):
                K_cof[i,k] = K_cof[i,k] + C[i,j,k,l]*nn[j]*nn[l]

In [5]:
# Levi-Civita Tensor

epsilon_LC = np.zeros((3,3,3))
epsilon_LC[0,1,2] = 1
epsilon_LC[1,2,0] = 1
epsilon_LC[2,0,1] = 1
epsilon_LC[0,2,1] = -1
epsilon_LC[1,0,2] = -1
epsilon_LC[2,1,0] = -1

In [6]:
# D-determinant

D = 0
for i in range(3):
    for j in range(3):
        for k in range(3):
            D = D + epsilon_LC[i,j,k]*K_cof[i,0]*K_cof[j,1]*K_cof[k,2]

In [7]:
# N matrix
N = np.zeros((3,3))

for i in range(3):
    for j in range(3):
        for k in range(3):
            for l in range(3):
                for m in range(3):
                    for n in range(3):
                        N[i,j] = N[i,j] + epsilon_LC[i,k,l]*epsilon_LC[j,m,n]*K_cof[k,m]*K_cof[l,n]*0.5

In [8]:
# Eq. 16
jmag = np.zeros((3,1))
jmag1 = 0
jmag2 = 0
jmag3 = 0

for i in range(3):
    for j in range(3):
        for k in range(3):
            for m in range(3):
                for n in range(3):
                    jmag[i] = -(jmag[i] + C[j,k,m,n]*epss[m,n]*nn[k]*N[i,j]/D)

print(jmag)

eps = np.zeros((3,3))
eps11 = 0
eps22 = 0
eps33 = 0
eps12 = 0
eps23 = 0
eps13 = 0

[[-0.00185714]
 [-0.        ]
 [-0.        ]]


In [9]:
# Eq. 20

for i in range(3):
    for j in range(3):
        eps[i,j] = jmag[i]*nn[j]
tot_eps = np.zeros((3,3))
tot_eps = eps + epss

In [10]:
# Eq. 21
jump_fac = np.zeros((3,3))

jump_fac11 = 0
jump_fac22 = 0
jump_fac33 = 0
jump_fac12 = 0
jump_fac23 = 0
jump_fac13 = 0

for k in range(3):
    for l in range(3):
        jump_fac11 = jump_fac11 + C[0,0,k,l]*tot_eps[k,l]
        jump_fac22 = jump_fac22 + C[1,1,k,l]*tot_eps[k,l]
        jump_fac33 = jump_fac33 + C[2,2,k,l]*tot_eps[k,l]
        jump_fac12 = jump_fac12 + C[0,1,k,l]*tot_eps[k,l]
        jump_fac23 = jump_fac23 + C[1,2,k,l]*tot_eps[k,l]
        jump_fac13 = jump_fac13 + C[0,2,k,l]*tot_eps[k,l]

jump_fac[0,0] = jump_fac11
jump_fac[1,1] = jump_fac22
jump_fac[2,2] = jump_fac33
jump_fac[0,1] = jump_fac12
jump_fac[1,2] = jump_fac23
jump_fac[0,2] = jump_fac13
jump_fac[1,0] = jump_fac12
jump_fac[2,1] = jump_fac23
jump_fac[2,0] = jump_fac13

sig_out = np.zeros((3,3))

print(sig_in)

sig_out = sig_in + jump_fac
print(sig_out)

[[-0.22908004 -0.         -0.        ]
 [-0.         -0.22908004 -0.        ]
 [-0.         -0.         -0.14183992]]
[[-0.22908004  0.          0.        ]
 [ 0.          0.07091996  0.        ]
 [ 0.          0.          0.15816008]]
